# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: onhub_diagnostic.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='onhub_diagnostic.proto',
  package='onhub_diagnostic',
  syntax='proto2',
  serialized_pb=_b('\n\x16onhub_diagnostic.proto\x12\x10onhub_diagnostic\"\xc6\x04\n\x06report\x12\r\n\x05\x62uild\x18\x01 \x02(\t\x12/\n\x05\x66iles\x18\x02 \x03(\x0b\x32 .onhub_diagnostic.report.catFile\x12\x0e\n\x06osname\x18\x03 \x02(\t\x12\x11\n\tnaString1\x18\x04 \x02(\t\x12\x10\n\x08naBytes1\x18\x05 \x02(\x0c\x12.\n\x06mounts\x18\x07 \x03(\x0b\x32\x1e.onhub_diagnostic.report.mount\x12\x11\n\tnaConfig1\x18\x08 \x02(\x0c\x12\x35\n\x08\x63ommands\x18\t \x03(\x0b\x32#.onhub_diagnostic.report.commandRan\x12\x11\n\tnaConfig2\x18\n \x02(\x0c\x12\x0e\n\x06naInt1\x18\x0b \x02(\r\x12:\n\tumessages\x18\x0c \x03(\x0b\x32\'.onhub_diagnostic.report.unknownMessage\x12\x0e\n\x06naInt2\x18\r \x02(\r\x1a)\n\x07\x63\x61tFile\x12\x0c\n\x04path\x18\x01 \x02(\t\x12\x10\n\x08\x63ontents\x18\x02 \x02(\x0c\x1a#\n\x05mount\x12\x0c\n\x04path\x18\x01 \x02(\t\x12\x0c\n\x04size\x18\x02 \x02(\r\x1a=\n\ncommandRan\x12\x0f\n\x07\x63ommand\x18\x01 \x02(\t\x12\x0e\n\x06stdout\x18\x02 \x02(\x0c\x12\x0e\n\x06retval\x18\x03 \x02(\x05\x1a#\n\x14unknownNestedMessage\x12\x0b\n\x03num\x18\x06 \x03(\r\x1a*\n\x0eunknownMessage\x12\x0b\n\x03hex\x18\x01 \x02(\t\x12\x0b\n\x03wat\x18\x02 \x02(\x0c')
)




_REPORT_CATFILE = _descriptor.Descriptor(
  name='catFile',
  full_name='onhub_diagnostic.report.catFile',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='path', full_name='onhub_diagnostic.report.catFile.path', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='contents', full_name='onhub_diagnostic.report.catFile.contents', index=1,
      number=2, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=405,
  serialized_end=446,
)

_REPORT_MOUNT = _descriptor.Descriptor(
  name='mount',
  full_name='onhub_diagnostic.report.mount',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='path', full_name='onhub_diagnostic.report.mount.path', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='size', full_name='onhub_diagnostic.report.mount.size', index=1,
      number=2, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=448,
  serialized_end=483,
)

_REPORT_COMMANDRAN = _descriptor.Descriptor(
  name='commandRan',
  full_name='onhub_diagnostic.report.commandRan',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='command', full_name='onhub_diagnostic.report.commandRan.command', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='stdout', full_name='onhub_diagnostic.report.commandRan.stdout', index=1,
      number=2, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='retval', full_name='onhub_diagnostic.report.commandRan.retval', index=2,
      number=3, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=485,
  serialized_end=546,
)

_REPORT_UNKNOWNNESTEDMESSAGE = _descriptor.Descriptor(
  name='unknownNestedMessage',
  full_name='onhub_diagnostic.report.unknownNestedMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='num', full_name='onhub_diagnostic.report.unknownNestedMessage.num', index=0,
      number=6, type=13, cpp_type=3, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=548,
  serialized_end=583,
)

_REPORT_UNKNOWNMESSAGE = _descriptor.Descriptor(
  name='unknownMessage',
  full_name='onhub_diagnostic.report.unknownMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='hex', full_name='onhub_diagnostic.report.unknownMessage.hex', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='wat', full_name='onhub_diagnostic.report.unknownMessage.wat', index=1,
      number=2, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=585,
  serialized_end=627,
)

_REPORT = _descriptor.Descriptor(
  name='report',
  full_name='onhub_diagnostic.report',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='build', full_name='onhub_diagnostic.report.build', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='files', full_name='onhub_diagnostic.report.files', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='osname', full_name='onhub_diagnostic.report.osname', index=2,
      number=3, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='naString1', full_name='onhub_diagnostic.report.naString1', index=3,
      number=4, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='naBytes1', full_name='onhub_diagnostic.report.naBytes1', index=4,
      number=5, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='mounts', full_name='onhub_diagnostic.report.mounts', index=5,
      number=7, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='naConfig1', full_name='onhub_diagnostic.report.naConfig1', index=6,
      number=8, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='commands', full_name='onhub_diagnostic.report.commands', index=7,
      number=9, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='naConfig2', full_name='onhub_diagnostic.report.naConfig2', index=8,
      number=10, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='naInt1', full_name='onhub_diagnostic.report.naInt1', index=9,
      number=11, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='umessages', full_name='onhub_diagnostic.report.umessages', index=10,
      number=12, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='naInt2', full_name='onhub_diagnostic.report.naInt2', index=11,
      number=13, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_REPORT_CATFILE, _REPORT_MOUNT, _REPORT_COMMANDRAN, _REPORT_UNKNOWNNESTEDMESSAGE, _REPORT_UNKNOWNMESSAGE, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=45,
  serialized_end=627,
)

_REPORT_CATFILE.containing_type = _REPORT
_REPORT_MOUNT.containing_type = _REPORT
_REPORT_COMMANDRAN.containing_type = _REPORT
_REPORT_UNKNOWNNESTEDMESSAGE.containing_type = _REPORT
_REPORT_UNKNOWNMESSAGE.containing_type = _REPORT
_REPORT.fields_by_name['files'].message_type = _REPORT_CATFILE
_REPORT.fields_by_name['mounts'].message_type = _REPORT_MOUNT
_REPORT.fields_by_name['commands'].message_type = _REPORT_COMMANDRAN
_REPORT.fields_by_name['umessages'].message_type = _REPORT_UNKNOWNMESSAGE
DESCRIPTOR.message_types_by_name['report'] = _REPORT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

report = _reflection.GeneratedProtocolMessageType('report', (_message.Message,), dict(

  catFile = _reflection.GeneratedProtocolMessageType('catFile', (_message.Message,), dict(
    DESCRIPTOR = _REPORT_CATFILE,
    __module__ = 'onhub_diagnostic_pb2'
    # @@protoc_insertion_point(class_scope:onhub_diagnostic.report.catFile)
    ))
  ,

  mount = _reflection.GeneratedProtocolMessageType('mount', (_message.Message,), dict(
    DESCRIPTOR = _REPORT_MOUNT,
    __module__ = 'onhub_diagnostic_pb2'
    # @@protoc_insertion_point(class_scope:onhub_diagnostic.report.mount)
    ))
  ,

  commandRan = _reflection.GeneratedProtocolMessageType('commandRan', (_message.Message,), dict(
    DESCRIPTOR = _REPORT_COMMANDRAN,
    __module__ = 'onhub_diagnostic_pb2'
    # @@protoc_insertion_point(class_scope:onhub_diagnostic.report.commandRan)
    ))
  ,

  unknownNestedMessage = _reflection.GeneratedProtocolMessageType('unknownNestedMessage', (_message.Message,), dict(
    DESCRIPTOR = _REPORT_UNKNOWNNESTEDMESSAGE,
    __module__ = 'onhub_diagnostic_pb2'
    # @@protoc_insertion_point(class_scope:onhub_diagnostic.report.unknownNestedMessage)
    ))
  ,

  unknownMessage = _reflection.GeneratedProtocolMessageType('unknownMessage', (_message.Message,), dict(
    DESCRIPTOR = _REPORT_UNKNOWNMESSAGE,
    __module__ = 'onhub_diagnostic_pb2'
    # @@protoc_insertion_point(class_scope:onhub_diagnostic.report.unknownMessage)
    ))
  ,
  DESCRIPTOR = _REPORT,
  __module__ = 'onhub_diagnostic_pb2'
  # @@protoc_insertion_point(class_scope:onhub_diagnostic.report)
  ))
_sym_db.RegisterMessage(report)
_sym_db.RegisterMessage(report.catFile)
_sym_db.RegisterMessage(report.mount)
_sym_db.RegisterMessage(report.commandRan)
_sym_db.RegisterMessage(report.unknownNestedMessage)
_sym_db.RegisterMessage(report.unknownMessage)


# @@protoc_insertion_point(module_scope)
